### ISSUE TITLE
Install fails with error.

### ISSUE THREAD

**Issue by Moghi** [ctorgalson/ansible-role-oh-my-zsh#15]
Hi,

I was happy to find this role, but when I tried to install it and I got the following:
```
$ ansible-galaxy install ctorgalson.oh-my-zsh
Starting galaxy role install process
- downloading role 'oh-my-zsh', owned by ctorgalson
[WARNING]: - ctorgalson.oh-my-zsh was NOT installed successfully: Unable to compare role
versions (1.0.0, 1.0.1, 1.0.2, 1.0.3, 2.0.0, 2.0.1, 2.1.0, 2.1.1, v2.2.0, v2.2.1, v2.2.2) to determine the
most recent version due to incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role  version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Following the error message and running the install with a specified version seems to work:
```
$ ansible-galaxy install ctorgalson.oh-my-zsh,v2.2.2
Starting galaxy role install process
- downloading role 'oh-my-zsh', owned by ctorgalson
- downloading role from https://github.com/ctorgalson/ansible-role-oh-my-zsh/archive/v2.2.2.tar.gz
- extracting ctorgalson.oh-my-zsh to /Users/moghi/proj_test/ansible/roles/ctorgalson.oh-my-zsh
- ctorgalson.oh-my-zsh (v2.2.2) was installed successfully
```

Thank you

Ansible v2.10.7

**Comment by ctorgalson** [comment]
Hi @Moghi,

Galaxy is aggravating :roll_eyes:. Anyway, I've renamed all the tags whose names didn't begin with `v` and reimported the role to Galaxy. I've tested installing with no version number, and it works.

This _will_ break things for anyone still using a requirements file with a value of `2.1.1` or earlier, but those are _quite_ old anyway ( and let's face it: this role isn't super-popular :grinning: )

**Comment by Moghi** [comment]
Thank you. I was happy to find this role here and appreciate your work.
